[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "6.0.11"
influxdb_rs = "0.2.1"
tokio = { version = "1.35.1", features = ["full"] }
url = "2.5.0"
warp = "0.3"

[profile.dev]
debug = 1

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
